# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b154bf56b3001d8a4a77c359cb67e1f77d5606d1aa5b01f774859c34fa9903ea9927360b8ee1457075c19b44ed92a9142095aad9b56f160f0431fd7645d493f1

test:
  secret_key_base: 7d93b5883a17eb13b8e131ef27496987c88c8efaabfdd54011e93a2ea72b7cd2cf09afd7f406b71df7a9bc75de8c9559a6c9ae877e977d1d3eaf8e3096916923

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
